spring.datasource.url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password: testtest
spring.datasource.max-active: 100
spring.datasource.time-between-execution-runs-millis: 30000
#spring.datasource.validation-query: "SELECT 1"
spring.datasource.initial-size: 10
spring.datasource.max-idle: 10
spring.datasource.min-execution-runs: 10
spring.datasource.remove-abandoned: true
spring.datasource.remove-abandoned-timeout: 60
#spring.datasource.
spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.order_inserts: true
#spring.jpa.properties.hibernate.batch_versioned_data: true
#spring.jpa.hibernate.jdbc.batch_size: 100
spring.jpa.show-sql: false
spring.jpa.open-in-view: false
#logging.level.com.zaxxer.hikari: debug
spring.thymeleaf.cache: false
spring.main.banner-mode: off
  
logging.file.name: logs/app.log
logging.level.org.springframework.web: INFO
logging.level.root: INFO
logging.file.max-size: 1MB
logging.file.total-size-cap: 10MB
logging.logback.rollingpolicy.clean-history-on-start: true
spring.output.ansi.enabled: ALWAYS


indexing-settings.sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://volochek.life
      name: Volochek.Life

server.port: 8080
